- hosts: all
   become: yes
   become_method: sudo
   become_user: root

   tasks:
     - name: install apache on ubuntu
       apt:
        name: apache2
        state: latest
        update_cache: yes
       when: ansible_distribution=="Ubuntu"

     - name: install apache on redhat
       yum:
        name: httpd
        state: latest
        update_cache: yes
       when: ansible_distribution=="RedHat"

     - name: enable the service
       service:
          enabled: true
          name: apache2
          state: started
       when: ansible_distribution=="Ubuntu"
     - name: enable the service
       service:
          enabled: true
          name: httpd
          state: started
       when: ansible_distribution=="RedHat"

     - name: copy the index.html to remote server
       copy:
        src: /etc/ansible/files/index.html
        dest: /var/www/html/index.html
